
// Generated by MyGeneration Version # (1.2.0.7)
using DAL;
using System;

namespace BLL
{
	public class PaymentTerm : _PaymentTerm
	{
		public PaymentTerm()
		{
		
		}

        public static int Internal { get { return GetPaymentTermIDByCode("INT"); } }
	    public static int GetPaymentTermIDByCode (string Code)
	    {
	        var paymentterm = new PaymentTerm();
	        var query = string.Format(@"select * from PaymentTerm where PaymentTermCode ='{0}'", Code);
	        paymentterm.LoadFromRawSql(query);
	        return paymentterm.ID;
	    }
	}
}
