
// Generated by MyGeneration Version # (1.3.0.9)

using System;
using System.Collections.Generic;

namespace Proxy
{
	public class DrugCategory 
	{
	
	#region Properties
	
		private  int? _ID;
		public  int? ID
	    {
			get
	        {
				return _ID;
			}
			set
	        {
				_ID = value;
			}
		}

		private  string _CategoryName;
		public  string CategoryName
	    {
			get
	        {
				return _CategoryName;
			}
			set
	        {
				_CategoryName = value;
			}
		}

		private  string _CategoryCode;
		public  string CategoryCode
	    {
			get
	        {
				return _CategoryCode;
			}
			set
	        {
				_CategoryCode = value;
			}
		}

		private  string _Description;
		public  string Description
	    {
			get
	        {
				return _Description;
			}
			set
	        {
				_Description = value;
			}
		}

		private  bool? _IsDeleted;
		public  bool? IsDeleted
	    {
			get
	        {
				return _IsDeleted;
			}
			set
	        {
				_IsDeleted = value;
			}
		}

		private  DateTime? _UpdateTime;
		public  DateTime? UpdateTime
	    {
			get
	        {
				return _UpdateTime;
			}
			set
	        {
				_UpdateTime = value;
			}
		}


	#endregion
	
    //#region Web Service Getters
		
    //    public static List<DrugCategory> GetAll()
    //    {
    //        BLL.DrugCategory v = new BLL.DrugCategory();
    //        v.LoadAll();
    //        return ToList(v);
    //    }
		
    //    public static List<DrugCategory> GetUpdatesAfter(long? lastVersion,DateTime? lastUpdateTime)
    //    {
    //        BLL.DrugCategory v = new BLL.DrugCategory();
    //        if(lastVersion.HasValue && lastVersion.Value != 0)
    //        {
    //            v.LoadUpdatesAfter( lastVersion.Value );    
    //        }else if(lastUpdateTime.HasValue)
    //        {
    //            v.LoadUpdatesAfterByTime(lastUpdateTime.Value);
    //        }else
    //        {
    //            v.LoadAll();
    //        }
    //        return ToList(v);
    //    }
		
    //    public static List<int> GetDeletedIDsAfter(long LastVersion)
    //    {
    //         BLL.DrugCategory v = new BLL.DrugCategory();
    //        v.LoadDeletedIDs(LastVersion);
    //        List<int> list = new List<int>();
    //        while (!v.EOF)
    //        {
    //            list.Add((int)v.GetColumn("ID"));
    //            v.MoveNext();
    //        }
    //        return list;
    //    }
		
    //#endregion
	
	
	
	#region Utilities
	
		
		#endregion
		
		
		#region Web service Saving

        public static void SaveList(List<HCMIS.Desktop.DirectoryServices.DrugCategory> list)
        {
            BLL.Category bv = new BLL.Category();
            foreach (HCMIS.Desktop.DirectoryServices.DrugCategory v in list)
            {
                // try to load by primary key
                bv.LoadByPrimaryKey(v.ID.Value);

                // if the entry doesn't exist, create it
                if (bv.RowCount == 0)
                {
                    bv.AddNew();
                }
                // populate the contents of v on the to the database list
              if( v.ID.HasValue )
				   bv.ID = v.ID.Value;
              if( v.CategoryName != "" && v.CategoryName != null )
				   bv.CategoryName = v.CategoryName;
              if( v.CategoryCode != "" && v.CategoryCode != null )
				   bv.CategoryCode = v.CategoryCode;
              if( v.Description != "" && v.Description != null )
				   bv.Description = v.Description;
              //if( v.IsDeleted.HasValue )
              //     bv.IsDeleted = v.IsDeleted.Value;
              //if( v.UpdateTime.HasValue )
              //     bv.UpdateTime = v.UpdateTime.Value;

                bv.Save();
            }


        }
	
	public static void DeleteList(List<int> list)
        {
            BLL.Category bv = new BLL.Category();
            foreach (int v in list)
            {
                // try to load by primary key
                bv.LoadByPrimaryKey(v);
                // if the entry doesn't exist, create it
                if (bv.RowCount > 0)
                {
                    bv.MarkAsDeleted();
					bv.Save();
                }
                // populate the contents of v on the to the database list

            }


        }
	
	
	#endregion
	}
}
