
// Generated by MyGeneration Version # (1.3.0.9)

using System;
using System.Collections.Generic;

namespace Proxy
{
	public class VEN 
	{
	
	#region Properties
	
		private  int? _ID;
		public  int? ID
	    {
			get
	        {
				return _ID;
			}
			set
	        {
				_ID = value;
			}
		}

		private  string _Value;
		public  string Value
	    {
			get
	        {
				return _Value;
			}
			set
	        {
				_Value = value;
			}
		}

		private  string _Description;
		public  string Description
	    {
			get
	        {
				return _Description;
			}
			set
	        {
				_Description = value;
			}
		}

		private  bool? _IsDeleted;
		public  bool? IsDeleted
	    {
			get
	        {
				return _IsDeleted;
			}
			set
	        {
				_IsDeleted = value;
			}
		}

		private  DateTime? _UpdateTime;
		public  DateTime? UpdateTime
	    {
			get
	        {
				return _UpdateTime;
			}
			set
	        {
				_UpdateTime = value;
			}
		}


	#endregion
	
	#region Web Service Getters
		
		public static List<VEN> GetAll()
        {
            BLL.VEN v = new BLL.VEN();
            v.LoadAll();
			return ToList(v);
        }
		
		public static List<VEN> GetUpdatesAfter(long? lastVersion,DateTime? lastUpdateTime)
        {
            BLL.VEN v = new BLL.VEN();
            if(lastVersion.HasValue && lastVersion.Value != 0)
            {
                v.LoadUpdatesAfter( Convert.ToInt32(lastVersion.Value) );    
            }else if(lastUpdateTime.HasValue)
            {
               // v.LoadUpdatesAfterByTime(lastUpdateTime.Value);
            }else
            {
                v.LoadAll();
            }
			return ToList(v);
        }
		
        public static List<int> GetDeletedIDsAfter(long LastVersion)
        {
             BLL.VEN v = new BLL.VEN();
            //v.LoadDeletedIDs(LastVersion);
            List<int> list = new List<int>();
            while (!v.EOF)
            {
                list.Add((int)v.GetColumn("ID"));
                v.MoveNext();
            }
            return list;
        }
		
	#endregion
	
	
	
	#region Utilities
	
		public static List<VEN> ToList(BLL.VEN v){
			List<VEN> list = new List<VEN>();
            while (!v.EOF)
            {
                VEN t = new VEN();
              if(!v.IsColumnNull("ID"))
				    t.ID = v.ID;
              if(!v.IsColumnNull("Value"))
				    t.Value = v.Value;
              if(!v.IsColumnNull("Description"))
				    t.Description = v.Description;
              //if(!v.IsColumnNull("IsDeleted"))
              //      t.IsDeleted = v.IsDeleted;
              //if(!v.IsColumnNull("UpdateTime"))
              //      t.UpdateTime = v.UpdateTime;

				list.Add(t);
                v.MoveNext();
            }
            return list;
		}
	
		#endregion
		
		
		#region Web service Saving

        public static void SaveList(List<HCMIS.Desktop.DirectoryServices.VEN> list)
        {
            BLL.VEN bv = new BLL.VEN();
            foreach (HCMIS.Desktop.DirectoryServices.VEN v in list)
            {
                // try to load by primary key
                bv.LoadByPrimaryKey(v.ID.Value);

                // if the entry doesn't exist, create it
                if (bv.RowCount == 0)
                {
                    bv.AddNew();
                }
                // populate the contents of v on the to the database list
              if( v.ID.HasValue )
				   bv.ID = v.ID.Value;
              if( v.Value != "" && v.Value != null )
				   bv.Value = v.Value;
              if( v.Description != "" && v.Description != null )
				   bv.Description = v.Description;
              //if( v.IsDeleted.HasValue )
              //     bv.IsDeleted = v.IsDeleted.Value;
              //if( v.UpdateTime.HasValue )
              //     bv.UpdateTime = v.UpdateTime.Value;

                bv.Save();
            }


        }
	
	public static void DeleteList(List<int> list)
        {
            BLL.VEN bv = new BLL.VEN();
            foreach (int v in list)
            {
                // try to load by primary key
                bv.LoadByPrimaryKey(v);
                // if the entry doesn't exist, create it
                if (bv.RowCount > 0)
                {
                    bv.MarkAsDeleted();
					bv.Save();
                }
                // populate the contents of v on the to the database list

            }


        }
	
	
	#endregion
	}
}
