using HCMIS.Extensions.Enums.Attributes;
namespace HCMIS.Enums
{
    [CodeColumn("ActivityCode")]
    public enum Activities
    {
       [TableCode("RCC1")] 
        RCC1,
       [TableCode("RCC2")] 
        RCC2,
       [TableCode("ARV")] 
        ARV,
       [TableCode("OI")] 
        OI,
       [TableCode("IP")] 
        IP,
       [TableCode("STI")] 
        STI,
       [TableCode("FH")] 
        FamilyHealth,
       [TableCode("NUT")] 
        Nutrition,
       [TableCode("KHP")] 
        KitHealthPost,
       [TableCode("MLR")] 
        Malaria,
       [TableCode("SP")] 
        SprayPump,
       [TableCode("OI2")] 
        OI2,
       [TableCode("TB")] 
        TB,
       [TableCode("MLR2")] 
        Malaria2,
       [TableCode("FM2")] 
        FamilyHealth2,
       [TableCode("ACP")] 
        ACP,
       [TableCode("FM3")] 
        FamilyHealth3,
       [TableCode("HSP")] 
        HSP,
       [TableCode("ICCM")] 
        ICCM,
       [TableCode("MLR3")] 
        Malaria3,
       [TableCode("NTD")] 
        NeglectedTD,
       [TableCode("NUT2")] 
        Nutrition2,
       [TableCode("CAN")] 
        Cancer,
       [TableCode("EMRG")] 
        Emergency,
       [TableCode("FA")] 
        FA,
       [TableCode("LPR")] 
        Leprosy,
       [TableCode("NBPP")] 
        NBPP,
       [TableCode("OI3")] 
        OI3,
       [TableCode("TB2")] 
        TB2,
       [TableCode("UNICF")] 
        UNICEF,
       [TableCode("VAC")] 
        Vaccine,
       [TableCode("CF")] 
        ClintonFoundation,
       [TableCode("RDFR")] 
        RDFRegular,
       [TableCode("RDFP")] 
        RDFPBS,
       [TableCode("RDFM")] 
        RDFMDG,
       [TableCode("GFC")] 
        GFConsignment,
       [TableCode("KIT")] 
        Kit,
       [TableCode("CR")] 
        ChemicalandReagent,
       [TableCode("GF")] 
        GF,
       [TableCode("VAC2")] 
        Vaccine2,
       [TableCode("INSU")] 
        Insulin,
       [TableCode("MEDE")] 
        Medicalequipment,
       [TableCode("BNU")] 
        BedNetUNICEFHeadOffice,
       [TableCode("EPRM")] 
        EPHARM,
       [TableCode("FMD")] 
        FMD,
       [TableCode("APF")] 
        APF,
       [TableCode("OTR")] 
        Other,
       [TableCode("VAC3")] 
        Vaccine3,
       [TableCode("CR2")] 
        ChemicalandReagent2,
       [TableCode("TB3")] 
        TB3,
       [TableCode("KHC")] 
        KitHealthCenter,
       [TableCode("OTR2")] 
        Others2,
       [TableCode("OTR3")] 
        Others3,
       [TableCode("MAL4")] 
        Malaria4,
       [TableCode("LABS")] 
        Labs,
       [TableCode("MDE")] 
        MillenniumDevelopmentEthiopia,
       [TableCode("GSC")] 
        GulleleSubcityWoreda7HealthCenter,
       [TableCode("CHBC")] 
        CHBC,
       [TableCode("NU3")] 
        Nutrition3,
       [TableCode("PMTCT")] 
        PMTCT,
       [TableCode("LAB")] 
        Lab,
       [TableCode("PMTC2")] 
        PMTCT2,
       [TableCode("MDE2")] 
        MedicalEquipment,
       [TableCode("INS")] 
        Insuline,
       [TableCode("TTYP")] 
        TTYPharmandMedPlc,
       [TableCode("SAP")] 
        SaronPharmachemi,
       [TableCode("TASH")] 
        TikuirAnbisaSpesaliziedHospital,
       [TableCode("MDE3")] 
        MedicalEquipment3,
       [TableCode("ERC")] 
        EthiopianRedCross,
       [TableCode("WH")] 
        WarehouseKitting,
       [TableCode("HCK")] 
        HealthCenterKit,
       [TableCode("SPH")] 
        StPaulosMillenniumMedicalCollegeSpecialHospital,
       [TableCode("SPP")] 
        StPaulosMillinumMedicalCollegeSpecialPharmacy,
       [TableCode("WP")] 
        WestPharm,
       [TableCode("PT")] 
        Petram,
       [TableCode("NON")] 
        NetofNet,
       [TableCode("MS")] 
        MedicalSupplies,
       [TableCode("RCC3")] 
        RCC3,
       [TableCode("NVA")] 
        NonVaccine,
       [TableCode("VCR")] 
        VaccineColdRoom,
       [TableCode("KTP")] 
        KidenyTransplant,

    }
}
