using HCMIS.Extensions.Enums.Attributes;
namespace HCMIS.Enums
{
    [CodeColumn("CategoryCode")]
    public enum Categories
    {
       [TableCode("00")] 
        Pharmaceutical,
       [TableCode("00")] 
        NonPharmaceutical,
       [TableCode("GI")] 
        Gastrointestinal,
       [TableCode("CV")] 
        Cardiovascular,
       [TableCode("RE")] 
        Respiratory,
       [TableCode("NS")] 
        CentralNervousSystem,
       [TableCode("AA")] 
        Anesthesia,
       [TableCode("MS")] 
        MusculoskeletalandJointDisease,
       [TableCode("AI")] 
        AntiInfectives,
       [TableCode("ED")] 
        EndocrineDisordersandContraceptives,
       [TableCode("OG")] 
        ObstetricandGynecologicalMedications,
       [TableCode("BL")] 
        BloodProductsandDrugsAffectingtheBlood,
       [TableCode("WE")] 
        CorrectingWaterElectrolyteandAcidBaseDistur,
       [TableCode("VT")] 
        Vitamins,
       [TableCode("AL")] 
        AntihistaminesandAntiallergics,
       [TableCode("OP")] 
        OphthalmicAgents,
       [TableCode("EN")] 
        EarNoseandThroatPreparations,
       [TableCode("DE")] 
        DermatologicalAgents,
       [TableCode("AD")] 
        AntidotesandOtherSubstancesusedinPoisoning,
       [TableCode("IM")] 
        ImmunologicalPreparations,
       [TableCode("MI")] 
        Miscellaneous,
       [TableCode("AN")] 
        AntineoplasticandAdjuvants,
       [TableCode("UR")] 
        UrologicalandRelateddrugs,
       [TableCode("LE")] 
        LaboratoryEquipment,
       [TableCode("00")] 
        MedicalInstruments,
       [TableCode("DM")] 
        MedicalSupplies,
       [TableCode("AI")] 
        ChemicalsandDiagnostics,
       [TableCode("200")] 
        AntiulcerAgents,
       [TableCode("300")] 
        AntispasmodicsspasmolyticAnalgesics,
       [TableCode("400")] 
        Antiemetics,
       [TableCode("500")] 
        CatharticsandLaxatives,
       [TableCode("600")] 
        DrugsUsedinDiarrhea,
       [TableCode("100")] 
        DrugsusedforCongestiveCardiacFailure,
       [TableCode("100")] 
        GeneralAnesthesia,
       [TableCode("700")] 
        Antiflatulents,
       [TableCode("800")] 
        Digestants,
       [TableCode("AA.200")] 
        NeuromuscularBlockers,
       [TableCode("CV.200")] 
        Antiarrhythmics,
       [TableCode("CV.300")] 
        AntilipemicAgents,
       [TableCode("CV.400")] 
        DrugsusedforanginaIschemicheartdisease,
       [TableCode("CV.500")] 
        Antihypertensives,
       [TableCode("CV.600")] 
        Diuretics,
       [TableCode("100")] 
        AntitussivesExpectorants,
       [TableCode("200")] 
        BronchodilatorsAntiasthmatics,
       [TableCode("NS.100")] 
        AnalgesicsAntipyretics,
       [TableCode("200")] 
        SedativesHypnoticsandTranquilizers,
       [TableCode("NS.300")] 
        Antidepressants,
       [TableCode("400")] 
        Anticonvulsants,
       [TableCode("NS.500")] 
        AntiparkinsonianDrugs,
       [TableCode("AA.300")] 
        AnestheticsAdjunctsandAdjuvants,
       [TableCode("AA.400")] 
        LocalAnaesthetics,
       [TableCode("MS.100")] 
        Antirheumatics,
       [TableCode("MS.200")] 
        Drugsusedforgout,
       [TableCode("900")] 
        AntihaemorrhoidalAgents,
       [TableCode("100")] 
        Antibacterials,
       [TableCode("101")] 
        Penicillins,
       [TableCode("102")] 
        OtherAntibacterials,
       [TableCode("AI.103")] 
        Antituberculars,
       [TableCode("AI.104")] 
        Antileprotics,
       [TableCode("200")] 
        Antifungals,
       [TableCode("ED.100")] 
        PituitaryHormonePreparations,
       [TableCode("ED.200")] 
        CorticosteroidalPreparations,
       [TableCode("CV.700")] 
        SclerosingAgents,
       [TableCode("CV.800")] 
        DrugsUsedinVascularShock,
       [TableCode("NS.600")] 
        CentralNervoussystemStimulant,
       [TableCode("AA.500")] 
        Others,
       [TableCode("MS.300")] 
        SkeletalMuscleRelaxants,
       [TableCode("MS.400")] 
        CholinergicandAnticholinesteraseAgents,
       [TableCode("MS.500")] 
        DrugsfortheReliefofsoftTissueInflammation,
       [TableCode("AI.300")] 
        ANTIVIRALS,
       [TableCode("301")] 
        AntiRetroViralARVAgents,
       [TableCode(".303")] 
        OtherAntivirals,
       [TableCode("AI.400")] 
        Antiprotozoals,
       [TableCode("401")] 
        Antimalarials,
       [TableCode("AI.402")] 
        Amoebicides,
       [TableCode("AI.403")] 
        AntigiardialAgents,
       [TableCode("AI.404")] 
        Leshmaniacides,
       [TableCode("AI.405")] 
        Trypanocides,
       [TableCode("AI.406")] 
        DrugsforToxoplasmosis,
       [TableCode("AI.500")] 
        Anthelmintics,
       [TableCode("AI.501")] 
        Filaricides,
       [TableCode("AI.502")] 
        Schistosomicides,
       [TableCode("AI.503")] 
        OtherAnthelmintics,
       [TableCode("ED.300")] 
        ThyroidHormonesandAntithyroidAgents,
       [TableCode("ED.400")] 
        InsulinandOralAntidiabeticAgents,
       [TableCode("ED.500")] 
        FemaleSexHormonesPreparations,
       [TableCode("ED.600")] 
        MaleSexHormonePreparations,
       [TableCode("ED.700")] 
        Contraceptives,
       [TableCode("ED.701")] 
        CombinedOralContraceptives,
       [TableCode("ED.702")] 
        ProgestogenOnlyContraceptives,
       [TableCode("ED.703")] 
        ContraceptiveDevicesBarriersandSpermicides,
       [TableCode("ED.900")] 
        DrugsusedforImpotence,
       [TableCode("BL.100")] 
        Anticoagulants,
       [TableCode("BL.200")] 
        HemostaticAgents,
       [TableCode("BL.300")] 
        AntianemicAgents,
       [TableCode("BL.400")] 
        BloodSubstitutesandPlasmaExpanders,
       [TableCode("100")] 
        Oral,
       [TableCode("200")] 
        Parenteral,
       [TableCode("WE.300")] 
        enteralNutrition,
       [TableCode("100")] 
        Vitaminssingle,
       [TableCode("VT.200")] 
        VitaminsCombinations,
       [TableCode("VT.201")] 
        VitaminBComplexPreparations,
       [TableCode("VT.202")] 
        MultivitaminPreparations,
       [TableCode("VT.203")] 
        MultivitaminwithMineralsandorExtracts,
       [TableCode("100")] 
        Antihistamines,
       [TableCode("200")] 
        DrugsUsedinAllergicEmergencies,
       [TableCode("OP.100")] 
        Antiglaucoma,
       [TableCode("200")] 
        MydriaticsCycloplegics,
       [TableCode("300")] 
        Anti–infectivesOphthalmic,
       [TableCode("OP.301")] 
        Antibacterials,
       [TableCode("OP.302")] 
        Antivirals,
       [TableCode("OP.303")] 
        Antifungals,
       [TableCode("OP.400")] 
        AntiInflammatories,
       [TableCode("OP.500")] 
        AntiInfectiveAntiinflammatoryCombination,
       [TableCode("OP.600")] 
        AnaestheticsLocal,
       [TableCode("OP.700")] 
        AntiallergicsDiagnosticsandMiscellaneousAgent,
       [TableCode("EN.100")] 
        NasalandOropharyngealPreparations,
       [TableCode("200")] 
        OticAgents,
       [TableCode("DE.100")] 
        AntiInfectiveTopical,
       [TableCode("DE.200")] 
        AntiInflammatoriesTopical,
       [TableCode("DE.250")] 
        AntiInfectiveAntiInflammatoryCombinations,
       [TableCode("DE.300")] 
        KeratolyticsCausticsandAntiacneAgents,
       [TableCode("DE.400")] 
        DrugsforPsoriasisandEezema,
       [TableCode("DE.500")] 
        Antiprurities,
       [TableCode("DE.600")] 
        PigmentingAgents,
       [TableCode("DE.700")] 
        Dermatologicalsystemic,
       [TableCode("DE.800")] 
        SkinDisinfectingAgents,
       [TableCode("DE.900")] 
        DermatologicalsOthers,
       [TableCode("OG.000")] 
        ObstetricandGynecologicalMedications,
       [TableCode("AD.000")] 
        AntidotesandOtherSubstancesusedin,
       [TableCode("000")] 
        ImmunologicalPreparations,
       [TableCode("00")] 
        UniversalAntidoteCharcoal+TannicAcid+Magnes,
       [TableCode("AI.301")] 
        ARVsTBD,
       [TableCode("000")] 
        Miscellaneous,
       [TableCode("BL.200")] 
        Antiplatelates,
       [TableCode("CV.900")] 
        ThrombolyticAgent,
       [TableCode("NS.700")] 
        DrugsforAttentionDeficitDisorder,
       [TableCode("Al.302")] 
        AntiHepatitis,
       [TableCode("000")] 
        AntineoplasticandAdjuvants,
       [TableCode("UR.100")] 
        DrugsusedforBenignprostaticHyperplasia,
       [TableCode("UR.200")] 
        Drugsusedforurinaryincontinence,
       [TableCode("00")] 
        Supplies,
       [TableCode("00")] 
        ARTSupplies,
       [TableCode("00")] 
        Consumables,
       [TableCode("00")] 
        LabOI,
       [TableCode("0")] 
        BiologicalStainsandIndicators,
       [TableCode("0")] 
        DiagonsticLaboratoryReagents,
       [TableCode("5")] 
        BacteriologicalMedias,
       [TableCode("1")] 
        ClinicalChemistryReagents,
       [TableCode("2")] 
        SerologyReagents,
       [TableCode("3")] 
        UrineTestStrips,
       [TableCode("6")] 
        XRayMaterialsandContrastMedias,
       [TableCode("0")] 
        GeneralLaboratoryChemicals,
       [TableCode("00")] 
        DentalInstruments,
       [TableCode("00")] 
        DiagnosticInstruments,
       [TableCode("00")] 
        ENTInstruments,
       [TableCode("00")] 
        GeneralSurgeryInstrument,
       [TableCode("00")] 
        GynecologicalandObstetricalInstruments,
       [TableCode("00")] 
        HospitalEquipment,
       [TableCode("00")] 
        KidneyandRectalInstruments,
       [TableCode("00")] 
        LaboratoryEquipment,
       [TableCode("00")] 
        OphthalmicInstrumentsandSupplies,
       [TableCode("00")] 
        OrthopedicInstruments,
       [TableCode("00")] 
        SpecialtyNeedlesforDiagnostic,
       [TableCode("00")] 
        ThoracicandCardiovascularInstruments,
       [TableCode("00")] 
        XrayMaterialsandXrayRoomEquipment,
       [TableCode("1000")] 
        ARTMedicalSupplies,
       [TableCode("3000")] 
        DressingMaterials,
       [TableCode("1000")] 
        HealthCareSuppliesandSurgicalBlades,
       [TableCode("4000")] 
        Miscellaneous,
       [TableCode("200")] 
        SuturingMaterials,
       [TableCode("TC.00.00")] 
        ThoracicandCardiovascular,
       [TableCode("BS")] 
        BiologicalStainsandIndicators,
       [TableCode("LC")] 
        GeneralLaboratoryChemicals,
       [TableCode("DE")] 
        Dentalinstruments,
       [TableCode("DI")] 
        DiagnosticInstruments,
       [TableCode("EI")] 
        ENTInstruments,
       [TableCode("GS")] 
        GeneralSurgeryInstrument,
       [TableCode("GO")] 
        GynecologicalandObstetricalInstruments,
       [TableCode("HE")] 
        HospitalEquipment,
       [TableCode("KR")] 
        KidneyandRectalInstruments,
       [TableCode("DR")] 
        DiagonsticLaboratoryReagents,
       [TableCode("4")] 
        BacteriologicalDrugSensitivityDisks,
       [TableCode("OP")] 
        OphthalmicInstrumentsandSupplies,
       [TableCode("OI")] 
        OrthopedicInstruments,
       [TableCode("SN")] 
        SpecialtyNeedlesForDiagnostic,
       [TableCode("XR")] 
        XrayMaterialsandXrayRoomEquipment,
       [TableCode("HS")] 
        HealthCareSuppliesandSurgicalBlades,
       [TableCode("SM")] 
        SuturingMaterials,

    }
}
