using HCMIS.Extensions.Enums.Attributes;
namespace HCMIS.Enums
{
    [CodeColumn("PackageCode")]
    public enum Packages
    {
       [TableCode("ABC")] 
        ABC,
       [TableCode("AC")] 
        Accounts,
       [TableCode("AU")] 
        AdministrativeUnits,
       [TableCode("CT")] 
        Category,
       [TableCode("CMT")] 
        CommodityType,
       [TableCode("CSM")] 
        CostingMethod,
       [TableCode("CR")] 
        Currency,
       [TableCode("DSF")] 
        DosageForm,
       [TableCode("MNF")] 
        Manufacturer,
       [TableCode("SP")] 
        EntitySupplier,
       [TableCode("EUAC")] 
        EUAccount,
       [TableCode("EUACP")] 
        EUAccountsPayable,
       [TableCode("EUACR")] 
        EUAccountsReceivable,
       [TableCode("EUCOS")] 
        EUCostOfSales,
       [TableCode("EUFAT")] 
        EUFixedAccountType,
       [TableCode("EUIN")] 
        EUInventory,
       [TableCode("EUS")] 
        EUSales,
       [TableCode("INS")] 
        InventoryStatus,
       [TableCode("IVT")] 
        InvoiceType,
       [TableCode("ITMM")] 
        ItemManufacturer,
       [TableCode("ITMPR")] 
        ItemProgram,
       [TableCode("ITMST")] 
        ItemStorageType,
       [TableCode("ITMS")] 
        ItemSupplier,
       [TableCode("LAAR")] 
        LossAndAdjustementReason,
       [TableCode("MBDT")] 
        MessageBrokerDocumentType,
       [TableCode("MAG")] 
        MovingAverageGroup,
       [TableCode("ORDS")] 
        OrderStatus,
       [TableCode("PMTT")] 
        PaymentTerm,
       [TableCode("ORDT")] 
        OrderType,
       [TableCode("OST")] 
        OwnershipType,
       [TableCode("PYTT")] 
        PaymentType,
       [TableCode("PR")] 
        Program,
       [TableCode("RCS")] 
        ReceiptConfirmationStatus,
       [TableCode("RT")] 
        ReceiptType,
       [TableCode("RQP")] 
        RequisitionPriority,
       [TableCode("RQS")] 
        RequisitionStatus,
       [TableCode("RQT")] 
        RequisitionType,
       [TableCode("STR")] 
        ShortageReason,
       [TableCode("STT")] 
        StorageType,
       [TableCode("TT")] 
        TransferType,
       [TableCode("UOF")] 
        UnitOfIssue,
       [TableCode("VN")] 
        VEN,
       [TableCode("FY")] 
        FiscalYear,
       [TableCode("PCT")] 
        PriceChangeType,
       [TableCode("JEV")] 
        JEvent
,
       [TableCode("CAC")] 
        CoreAccount,
       [TableCode("CACC")] 
        CoreAccountCategory
,
       [TableCode("VM")] 
        VolumeMetrics,
       [TableCode("RGE")] 
        RegionalEstimate,
       [TableCode("POP")] 
        Population,
       [TableCode("DMI")] 
        DemographicIndicator,
       [TableCode("IIT")] 
        InstitutionIType,
       [TableCode("IC")] 
        ItemCategory,
       [TableCode("IHTP")] 
        InstitutionHubtoPDS,
       [TableCode("IMCTP")] 
        ItemManufacturerCenterToPDS,
       [TableCode("ITINT")] 
        ItemInstitutionType,
       [TableCode("IACTP")] 
        ItemActivityCenterToPDS,
       [TableCode("IUWQT")] 
        ItemUnitWithQtyAndText,
       [TableCode("PRD")] 
        Product,
       [TableCode("IN")] 
        Institution,
       [TableCode("ITM")] 
        Item,
       [TableCode("INH")] 
        InstitutionHub,
       [TableCode("EURT")] 
        EUReceiptType,
       [TableCode("MI")] 
        MenuItem,
       [TableCode("RST")] 
        ResourceType,
       [TableCode("JT")] 
        JobTitle,
       [TableCode("GRP")] 
        Group,
       [TableCode("DPT")] 
        Department,
       [TableCode("JCA")] 
        JEventCoreAccount,
       [TableCode("EINV")] 
        Inventory,
       //[TableCode("ERCT")] 
       // ReceiptType,
       [TableCode("MPT")] 
        ModePaymentType,
       [TableCode("INST")] 
        InstitutionType,
       [TableCode("SS")] 
        SoftwareSetting,
       [TableCode("ICA")] 
        InstitutionCatchmentArea,
       [TableCode("IND")] 
        Indicator,
       [TableCode("IOT")] 
        ItemOwnershipType,
       [TableCode("ICS")] 
        InstitutionClinicalService,
       [TableCode("CS")] 
        ClinicalService,
       [TableCode("UAC")] 
        Action,
       [TableCode("CCV")] 
        CommodityCommodityValue,
       [TableCode("SSCT")] 
        SoftwareSettingCategory,
       [TableCode("AUD")] 
        AdministrativeUnitAdministrativeUnitDirect,
       [TableCode("IMSTV")] 
        InventoryManagmentSTVDNSync,
       [TableCode("SSSN")] 
        SoftwareSettingsByName,
       [TableCode("SSCN")] 
        SettingSoftwareSettingCategoryByName,
       [TableCode("INPS")] 
        InventoryManagmentPOSync,

    }
}
