using HCMIS.Extensions.Enums.Attributes;
namespace HCMIS.Enums
{
    [CodeColumn("SiteCode")]
    public enum Sites
    {
       [TableCode("ADPH")] 
        AdamaHub,
       [TableCode("BDPH")] 
        BahirDarHub,
       [TableCode("BTM")] 
        BetaVM,
       [TableCode("CNPH")] 
        Center,
       [TableCode("DSPH")] 
        DessieHub,
       [TableCode("DDPH")] 
        DireDawaHub,
       [TableCode("GNPH")] 
        GondarHub,
       [TableCode("AAPH")] 
        AddisAbabaHub,
       [TableCode("HWPH")] 
        HawassaHub,
       [TableCode("JMPH")] 
        JimmaHub,
       [TableCode("JMPPH")] 
        JimmaProgramHub,
       [TableCode("MKPH")] 
        MekelleHub,
       [TableCode("AMM")] 
        Amazon,
       [TableCode("NBPH")] 
        NegeleBorenaHub,
       [TableCode("NKPH")] 
        NekemteHub,
       [TableCode("DVM")] 
        DevVM,
       [TableCode("ALM")] 
        AlphaVM,
       [TableCode("STM")] 
        StagingVM,
       [TableCode("SCM")] 
        SchemaVM,
       [TableCode("DUVH")] 
        DukemColdRoom,
       [TableCode("MKVH")] 
        MekelleColdRoom,
       [TableCode("JMVH")] 
        JimmaColdRoom,
       [TableCode("NKVH")] 
        NekemteColdRoom,
       [TableCode("BDVH")] 
        BahirDarColdRoom,
       [TableCode("DSVH")] 
        DessieColdRoom,
       [TableCode("HWVH")] 
        HawassaColdRoom,
       [TableCode("DDVH")] 
        DireDawaColdRoom,
       [TableCode("ASVH")] 
        AssosaColdRoom,
       [TableCode("CNTM")] 
        CenterTestVM,
       [TableCode("CHVH")] 
        ChiroColdRoom,
       [TableCode("CNVH")] 
        CentralColdRoom,
       [TableCode("MKTM")] 
        MekelleTestVM,
       [TableCode("HEM")] 
        BETA_HCMISWEmpty,

    }
}
