using HCMIS.Extensions.Enums.Attributes;
namespace HCMIS.Enums
{
    [CodeColumn("SoftwareSettingCode")]
    public enum SoftwareSettings
    {
       [TableCode("UM")] 
        UseMovingAverage,
       [TableCode("UH")] 
        UseHeadedPaper,
       [TableCode("MR")] 
        ModeRDF,
       [TableCode("UC")] 
        UseCustomSizedPaperForPrinting,
       [TableCode("PH")] 
        PaperHeight,
       [TableCode("PW")] 
        PaperWidth,
       [TableCode("ND")] 
        NoOfDigitsAfterTheDecimalPoint,
       [TableCode("PC")] 
        PrivateCanGetFromMDGAndPBS,
       [TableCode("PM")] 
        PrintMultipleCommodityTypesPerPage,
       [TableCode("HD")] 
        HandleDeliveryNotes,
       [TableCode("AP")] 
        AllowPreferredManufacturers,
       [TableCode("EB")] 
        EnforceBatchTracking,
       [TableCode("HG")] 
        HandleGRV,
       [TableCode("APE")] 
        AllowPreferredExpiry,
       [TableCode("APP")] 
        AllowPreferredPhysicalStore,
       [TableCode("IC")] 
        IsCenter,
       [TableCode("BE")] 
        BlockWhenExpectingPriceChange,
       [TableCode("IF")] 
        InsuranceFormula,
       [TableCode("SB")] 
        SkipBeginningBalancePricing,
       [TableCode("UR")] 
        UseReceiveCostConfirmation,
       [TableCode("UCS")] 
        UseCustomSizedPaperForPrintingCredit,
       [TableCode("PWC")] 
        PaperWidthCredit,
       [TableCode("PHC")] 
        PaperHeightCredit,
       [TableCode("NDP")] 
        NoOfDaysPicklistStaysAfterPrinting,
       [TableCode("IUP")] 
        IssueUnPricedCommodities,
       [TableCode("DB")] 
        DisableBeginningCosting,
       [TableCode("SM")] 
        ShowMultipleStoresOnSTV,
       [TableCode("DSB")] 
        DisableBeginningBalanceReceipt,
       [TableCode("SBB")] 
        ShowBeginningBalanceOnGRNF,
       [TableCode("SMS")] 
        ShowMissingSTVsOnIssueLog,
       [TableCode("UA")] 
        UseMovingAverageConfirmation,
       [TableCode("AC")] 
        AllowCustomIssueOrder,
       [TableCode("DI")] 
        DoNotIssueNearExpiryItems,
       [TableCode("CQ")] 
        CheckQuotaOnIssue,
       [TableCode("ID")] 
        IsDamageIncludedOnTotalFOB,
       [TableCode("DE")] 
        DisableInvoiceEditAfterStepNo,
       [TableCode("UN")] 
        UseNewUserManagement,
       [TableCode("US")] 
        UseSmallerCreditPrintout,
       [TableCode("UP")] 
        UseSmallerCashPrintout,
       [TableCode("UCP")] 
        UseCustomSizedPaperForPrintingCash,
       [TableCode("PEW")] 
        PaperWidthCash,
       [TableCode("PEH")] 
        PaperHeightCash,
       [TableCode("FR")] 
        FullyReservedItemsConsideredStockedOut,
       [TableCode("AO")] 
        AllowOnlineOrders,
       [TableCode("BT")] 
        BugTrackingURL,
       [TableCode("EBO")] 
        EnableBackOrders,
       [TableCode("AB")] 
        AllowBonusReceive,
       [TableCode("UCT")] 
        UseCostTier,
       [TableCode("ACE")] 
        AutoCancelExpiredPicklists,
       [TableCode("LT")] 
        LocalvsTender,
       [TableCode("GC")] 
        GRNFCopies,
       [TableCode("PN")] 
        PrintUserNameOnInvoice,
       [TableCode("SW")] 
        ShowAllForWishList,
       [TableCode("SC")] 
        STVCopies,

    }
}
