
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.2.0.7)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace DAL
{
	public abstract class _Group : SqlClientEntity
	{
		public _Group()
		{
			this.QuerySource = "Group";
			this.MappingName = "Group";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_GroupLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int GroupID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.GroupID, GroupID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_GroupLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter GroupID
			{
				get
				{
					return new SqlParameter("@GroupID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Name
			{
				get
				{
					return new SqlParameter("@Name", SqlDbType.NText, 1073741823);
				}
			}
			
			public static SqlParameter ParentID
			{
				get
				{
					return new SqlParameter("@ParentID", SqlDbType.Int, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string GroupID = "GroupID";
            public const string Name = "Name";
            public const string ParentID = "ParentID";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[GroupID] = _Group.PropertyNames.GroupID;
					ht[Name] = _Group.PropertyNames.Name;
					ht[ParentID] = _Group.PropertyNames.ParentID;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string GroupID = "GroupID";
            public const string Name = "Name";
            public const string ParentID = "ParentID";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[GroupID] = _Group.ColumnNames.GroupID;
					ht[Name] = _Group.ColumnNames.Name;
					ht[ParentID] = _Group.ColumnNames.ParentID;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string GroupID = "s_GroupID";
            public const string Name = "s_Name";
            public const string ParentID = "s_ParentID";

		}
		#endregion		
		
		#region Properties
	
		public virtual int GroupID
	    {
			get
	        {
				return base.Getint(ColumnNames.GroupID);
			}
			set
	        {
				base.Setint(ColumnNames.GroupID, value);
			}
		}

		public virtual string Name
	    {
			get
	        {
				return base.Getstring(ColumnNames.Name);
			}
			set
	        {
				base.Setstring(ColumnNames.Name, value);
			}
		}

		public virtual int ParentID
	    {
			get
	        {
				return base.Getint(ColumnNames.ParentID);
			}
			set
	        {
				base.Setint(ColumnNames.ParentID, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_GroupID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.GroupID) ? string.Empty : base.GetintAsString(ColumnNames.GroupID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.GroupID);
				else
					this.GroupID = base.SetintAsString(ColumnNames.GroupID, value);
			}
		}

		public virtual string s_Name
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Name) ? string.Empty : base.GetstringAsString(ColumnNames.Name);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Name);
				else
					this.Name = base.SetstringAsString(ColumnNames.Name, value);
			}
		}

		public virtual string s_ParentID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ParentID) ? string.Empty : base.GetintAsString(ColumnNames.ParentID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ParentID);
				else
					this.ParentID = base.SetintAsString(ColumnNames.ParentID, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter GroupID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.GroupID, Parameters.GroupID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Name
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ParentID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ParentID, Parameters.ParentID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter GroupID
		    {
				get
		        {
					if(_GroupID_W == null)
	        	    {
						_GroupID_W = TearOff.GroupID;
					}
					return _GroupID_W;
				}
			}

			public WhereParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public WhereParameter ParentID
		    {
				get
		        {
					if(_ParentID_W == null)
	        	    {
						_ParentID_W = TearOff.ParentID;
					}
					return _ParentID_W;
				}
			}

			private WhereParameter _GroupID_W = null;
			private WhereParameter _Name_W = null;
			private WhereParameter _ParentID_W = null;

			public void WhereClauseReset()
			{
				_GroupID_W = null;
				_Name_W = null;
				_ParentID_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter GroupID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.GroupID, Parameters.GroupID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Name
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Name, Parameters.Name);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ParentID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ParentID, Parameters.ParentID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter GroupID
		    {
				get
		        {
					if(_GroupID_W == null)
	        	    {
						_GroupID_W = TearOff.GroupID;
					}
					return _GroupID_W;
				}
			}

			public AggregateParameter Name
		    {
				get
		        {
					if(_Name_W == null)
	        	    {
						_Name_W = TearOff.Name;
					}
					return _Name_W;
				}
			}

			public AggregateParameter ParentID
		    {
				get
		        {
					if(_ParentID_W == null)
	        	    {
						_ParentID_W = TearOff.ParentID;
					}
					return _ParentID_W;
				}
			}

			private AggregateParameter _GroupID_W = null;
			private AggregateParameter _Name_W = null;
			private AggregateParameter _ParentID_W = null;

			public void AggregateClauseReset()
			{
				_GroupID_W = null;
				_Name_W = null;
				_ParentID_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_GroupInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.GroupID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_GroupUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_GroupDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.GroupID);
			p.SourceColumn = ColumnNames.GroupID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.GroupID);
			p.SourceColumn = ColumnNames.GroupID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Name);
			p.SourceColumn = ColumnNames.Name;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ParentID);
			p.SourceColumn = ColumnNames.ParentID;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
