
/*
'===============================================================================
'  Generated From - CSharp_dOOdads_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL        = SQL_StoredProcs.vbgen
'  ACCESS     = Access_StoredProcs.vbgen
'  ORACLE     = Oracle_StoredProcs.vbgen
'  FIREBIRD   = FirebirdStoredProcs.vbgen
'  POSTGRESQL = PostgreSQL_StoredProcs.vbgen
'
'  The supporting base class SqlClientEntity is in the Architecture directory in "dOOdads".
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easilly done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.2.0.7)

using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections;
using System.Collections.Specialized;

using MyGeneration.dOOdads;

namespace DAL
{
	public abstract class _LogRequisitionEvents : SqlClientEntity
	{
		public _LogRequisitionEvents()
		{
			this.QuerySource = "LogRequisitionEvents";
			this.MappingName = "LogRequisitionEvents";

		}	

		//=================================================================
		//  public Overrides void AddNew()
		//=================================================================
		//
		//=================================================================
		public override void AddNew()
		{
			base.AddNew();
			
		}
		
		
		public override void FlushData()
		{
			this._whereClause = null;
			this._aggregateClause = null;
			base.FlushData();
		}
		
		//=================================================================
		//  	public Function LoadAll() As Boolean
		//=================================================================
		//  Loads all of the records in the database, and sets the currentRow to the first row
		//=================================================================
		public bool LoadAll() 
		{
			ListDictionary parameters = null;
			
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_LogRequisitionEventsLoadAll]", parameters);
		}
	
		//=================================================================
		// public Overridable Function LoadByPrimaryKey()  As Boolean
		//=================================================================
		//  Loads a single row of via the primary key
		//=================================================================
		public virtual bool LoadByPrimaryKey(int ID)
		{
			ListDictionary parameters = new ListDictionary();
			parameters.Add(Parameters.ID, ID);

		
			return base.LoadFromSql("[" + this.SchemaStoredProcedure + "proc_LogRequisitionEventsLoadByPrimaryKey]", parameters);
		}
		
		#region Parameters
		protected class Parameters
		{
			
			public static SqlParameter ID
			{
				get
				{
					return new SqlParameter("@ID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter Identifier
			{
				get
				{
					return new SqlParameter("@Identifier", SqlDbType.UniqueIdentifier, 0);
				}
			}
			
			public static SqlParameter RequisitionID
			{
				get
				{
					return new SqlParameter("@RequisitionID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter EventName
			{
				get
				{
					return new SqlParameter("@EventName", SqlDbType.NVarChar, 1);
				}
			}
			
			public static SqlParameter EventDescription
			{
				get
				{
					return new SqlParameter("@EventDescription", SqlDbType.NVarChar, 1);
				}
			}
			
			public static SqlParameter UserID
			{
				get
				{
					return new SqlParameter("@UserID", SqlDbType.Int, 0);
				}
			}
			
			public static SqlParameter ByUserName
			{
				get
				{
					return new SqlParameter("@ByUserName", SqlDbType.NVarChar, 1);
				}
			}
			
			public static SqlParameter EventTime
			{
				get
				{
					return new SqlParameter("@EventTime", SqlDbType.DateTime, 0);
				}
			}
			
		}
		#endregion		
	
		#region ColumnNames
		public class ColumnNames
		{  
            public const string ID = "ID";
            public const string Identifier = "Identifier";
            public const string RequisitionID = "RequisitionID";
            public const string EventName = "EventName";
            public const string EventDescription = "EventDescription";
            public const string UserID = "UserID";
            public const string ByUserName = "ByUserName";
            public const string EventTime = "EventTime";

			static public string ToPropertyName(string columnName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[ID] = _LogRequisitionEvents.PropertyNames.ID;
					ht[Identifier] = _LogRequisitionEvents.PropertyNames.Identifier;
					ht[RequisitionID] = _LogRequisitionEvents.PropertyNames.RequisitionID;
					ht[EventName] = _LogRequisitionEvents.PropertyNames.EventName;
					ht[EventDescription] = _LogRequisitionEvents.PropertyNames.EventDescription;
					ht[UserID] = _LogRequisitionEvents.PropertyNames.UserID;
					ht[ByUserName] = _LogRequisitionEvents.PropertyNames.ByUserName;
					ht[EventTime] = _LogRequisitionEvents.PropertyNames.EventTime;

				}
				return (string)ht[columnName];
			}

			static private Hashtable ht = null;			 
		}
		#endregion
		
		#region PropertyNames
		public class PropertyNames
		{  
            public const string ID = "ID";
            public const string Identifier = "Identifier";
            public const string RequisitionID = "RequisitionID";
            public const string EventName = "EventName";
            public const string EventDescription = "EventDescription";
            public const string UserID = "UserID";
            public const string ByUserName = "ByUserName";
            public const string EventTime = "EventTime";

			static public string ToColumnName(string propertyName)
			{
				if(ht == null)
				{
					ht = new Hashtable();
					
					ht[ID] = _LogRequisitionEvents.ColumnNames.ID;
					ht[Identifier] = _LogRequisitionEvents.ColumnNames.Identifier;
					ht[RequisitionID] = _LogRequisitionEvents.ColumnNames.RequisitionID;
					ht[EventName] = _LogRequisitionEvents.ColumnNames.EventName;
					ht[EventDescription] = _LogRequisitionEvents.ColumnNames.EventDescription;
					ht[UserID] = _LogRequisitionEvents.ColumnNames.UserID;
					ht[ByUserName] = _LogRequisitionEvents.ColumnNames.ByUserName;
					ht[EventTime] = _LogRequisitionEvents.ColumnNames.EventTime;

				}
				return (string)ht[propertyName];
			}

			static private Hashtable ht = null;			 
		}			 
		#endregion	

		#region StringPropertyNames
		public class StringPropertyNames
		{  
            public const string ID = "s_ID";
            public const string Identifier = "s_Identifier";
            public const string RequisitionID = "s_RequisitionID";
            public const string EventName = "s_EventName";
            public const string EventDescription = "s_EventDescription";
            public const string UserID = "s_UserID";
            public const string ByUserName = "s_ByUserName";
            public const string EventTime = "s_EventTime";

		}
		#endregion		
		
		#region Properties
	
		public virtual int ID
	    {
			get
	        {
				return base.Getint(ColumnNames.ID);
			}
			set
	        {
				base.Setint(ColumnNames.ID, value);
			}
		}

		public virtual Guid Identifier
	    {
			get
	        {
				return base.GetGuid(ColumnNames.Identifier);
			}
			set
	        {
				base.SetGuid(ColumnNames.Identifier, value);
			}
		}

		public virtual int RequisitionID
	    {
			get
	        {
				return base.Getint(ColumnNames.RequisitionID);
			}
			set
	        {
				base.Setint(ColumnNames.RequisitionID, value);
			}
		}

		public virtual string EventName
	    {
			get
	        {
				return base.Getstring(ColumnNames.EventName);
			}
			set
	        {
				base.Setstring(ColumnNames.EventName, value);
			}
		}

		public virtual string EventDescription
	    {
			get
	        {
				return base.Getstring(ColumnNames.EventDescription);
			}
			set
	        {
				base.Setstring(ColumnNames.EventDescription, value);
			}
		}

		public virtual int UserID
	    {
			get
	        {
				return base.Getint(ColumnNames.UserID);
			}
			set
	        {
				base.Setint(ColumnNames.UserID, value);
			}
		}

		public virtual string ByUserName
	    {
			get
	        {
				return base.Getstring(ColumnNames.ByUserName);
			}
			set
	        {
				base.Setstring(ColumnNames.ByUserName, value);
			}
		}

		public virtual DateTime EventTime
	    {
			get
	        {
				return base.GetDateTime(ColumnNames.EventTime);
			}
			set
	        {
				base.SetDateTime(ColumnNames.EventTime, value);
			}
		}


		#endregion
		
		#region String Properties
	
		public virtual string s_ID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ID) ? string.Empty : base.GetintAsString(ColumnNames.ID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ID);
				else
					this.ID = base.SetintAsString(ColumnNames.ID, value);
			}
		}

		public virtual string s_Identifier
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.Identifier) ? string.Empty : base.GetGuidAsString(ColumnNames.Identifier);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.Identifier);
				else
					this.Identifier = base.SetGuidAsString(ColumnNames.Identifier, value);
			}
		}

		public virtual string s_RequisitionID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.RequisitionID) ? string.Empty : base.GetintAsString(ColumnNames.RequisitionID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.RequisitionID);
				else
					this.RequisitionID = base.SetintAsString(ColumnNames.RequisitionID, value);
			}
		}

		public virtual string s_EventName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.EventName) ? string.Empty : base.GetstringAsString(ColumnNames.EventName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.EventName);
				else
					this.EventName = base.SetstringAsString(ColumnNames.EventName, value);
			}
		}

		public virtual string s_EventDescription
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.EventDescription) ? string.Empty : base.GetstringAsString(ColumnNames.EventDescription);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.EventDescription);
				else
					this.EventDescription = base.SetstringAsString(ColumnNames.EventDescription, value);
			}
		}

		public virtual string s_UserID
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.UserID) ? string.Empty : base.GetintAsString(ColumnNames.UserID);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.UserID);
				else
					this.UserID = base.SetintAsString(ColumnNames.UserID, value);
			}
		}

		public virtual string s_ByUserName
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.ByUserName) ? string.Empty : base.GetstringAsString(ColumnNames.ByUserName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.ByUserName);
				else
					this.ByUserName = base.SetstringAsString(ColumnNames.ByUserName, value);
			}
		}

		public virtual string s_EventTime
	    {
			get
	        {
				return this.IsColumnNull(ColumnNames.EventTime) ? string.Empty : base.GetDateTimeAsString(ColumnNames.EventTime);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ColumnNames.EventTime);
				else
					this.EventTime = base.SetDateTimeAsString(ColumnNames.EventTime, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region WhereParameter TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter ID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ID, Parameters.ID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter Identifier
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.Identifier, Parameters.Identifier);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter RequisitionID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.RequisitionID, Parameters.RequisitionID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter EventName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.EventName, Parameters.EventName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter EventDescription
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.EventDescription, Parameters.EventDescription);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter UserID
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.UserID, Parameters.UserID);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter ByUserName
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.ByUserName, Parameters.ByUserName);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}

				public WhereParameter EventTime
				{
					get
					{
							WhereParameter where = new WhereParameter(ColumnNames.EventTime, Parameters.EventTime);
							this._clause._entity.Query.AddWhereParameter(where);
							return where;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter ID
		    {
				get
		        {
					if(_ID_W == null)
	        	    {
						_ID_W = TearOff.ID;
					}
					return _ID_W;
				}
			}

			public WhereParameter Identifier
		    {
				get
		        {
					if(_Identifier_W == null)
	        	    {
						_Identifier_W = TearOff.Identifier;
					}
					return _Identifier_W;
				}
			}

			public WhereParameter RequisitionID
		    {
				get
		        {
					if(_RequisitionID_W == null)
	        	    {
						_RequisitionID_W = TearOff.RequisitionID;
					}
					return _RequisitionID_W;
				}
			}

			public WhereParameter EventName
		    {
				get
		        {
					if(_EventName_W == null)
	        	    {
						_EventName_W = TearOff.EventName;
					}
					return _EventName_W;
				}
			}

			public WhereParameter EventDescription
		    {
				get
		        {
					if(_EventDescription_W == null)
	        	    {
						_EventDescription_W = TearOff.EventDescription;
					}
					return _EventDescription_W;
				}
			}

			public WhereParameter UserID
		    {
				get
		        {
					if(_UserID_W == null)
	        	    {
						_UserID_W = TearOff.UserID;
					}
					return _UserID_W;
				}
			}

			public WhereParameter ByUserName
		    {
				get
		        {
					if(_ByUserName_W == null)
	        	    {
						_ByUserName_W = TearOff.ByUserName;
					}
					return _ByUserName_W;
				}
			}

			public WhereParameter EventTime
		    {
				get
		        {
					if(_EventTime_W == null)
	        	    {
						_EventTime_W = TearOff.EventTime;
					}
					return _EventTime_W;
				}
			}

			private WhereParameter _ID_W = null;
			private WhereParameter _Identifier_W = null;
			private WhereParameter _RequisitionID_W = null;
			private WhereParameter _EventName_W = null;
			private WhereParameter _EventDescription_W = null;
			private WhereParameter _UserID_W = null;
			private WhereParameter _ByUserName_W = null;
			private WhereParameter _EventTime_W = null;

			public void WhereClauseReset()
			{
				_ID_W = null;
				_Identifier_W = null;
				_RequisitionID_W = null;
				_EventName_W = null;
				_EventDescription_W = null;
				_UserID_W = null;
				_ByUserName_W = null;
				_EventTime_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
	
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(BusinessEntity entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region AggregateParameter TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter ID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ID, Parameters.ID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter Identifier
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.Identifier, Parameters.Identifier);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter RequisitionID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.RequisitionID, Parameters.RequisitionID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter EventName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.EventName, Parameters.EventName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter EventDescription
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.EventDescription, Parameters.EventDescription);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter UserID
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.UserID, Parameters.UserID);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter ByUserName
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.ByUserName, Parameters.ByUserName);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}

				public AggregateParameter EventTime
				{
					get
					{
							AggregateParameter aggregate = new AggregateParameter(ColumnNames.EventTime, Parameters.EventTime);
							this._clause._entity.Query.AddAggregateParameter(aggregate);
							return aggregate;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter ID
		    {
				get
		        {
					if(_ID_W == null)
	        	    {
						_ID_W = TearOff.ID;
					}
					return _ID_W;
				}
			}

			public AggregateParameter Identifier
		    {
				get
		        {
					if(_Identifier_W == null)
	        	    {
						_Identifier_W = TearOff.Identifier;
					}
					return _Identifier_W;
				}
			}

			public AggregateParameter RequisitionID
		    {
				get
		        {
					if(_RequisitionID_W == null)
	        	    {
						_RequisitionID_W = TearOff.RequisitionID;
					}
					return _RequisitionID_W;
				}
			}

			public AggregateParameter EventName
		    {
				get
		        {
					if(_EventName_W == null)
	        	    {
						_EventName_W = TearOff.EventName;
					}
					return _EventName_W;
				}
			}

			public AggregateParameter EventDescription
		    {
				get
		        {
					if(_EventDescription_W == null)
	        	    {
						_EventDescription_W = TearOff.EventDescription;
					}
					return _EventDescription_W;
				}
			}

			public AggregateParameter UserID
		    {
				get
		        {
					if(_UserID_W == null)
	        	    {
						_UserID_W = TearOff.UserID;
					}
					return _UserID_W;
				}
			}

			public AggregateParameter ByUserName
		    {
				get
		        {
					if(_ByUserName_W == null)
	        	    {
						_ByUserName_W = TearOff.ByUserName;
					}
					return _ByUserName_W;
				}
			}

			public AggregateParameter EventTime
		    {
				get
		        {
					if(_EventTime_W == null)
	        	    {
						_EventTime_W = TearOff.EventTime;
					}
					return _EventTime_W;
				}
			}

			private AggregateParameter _ID_W = null;
			private AggregateParameter _Identifier_W = null;
			private AggregateParameter _RequisitionID_W = null;
			private AggregateParameter _EventName_W = null;
			private AggregateParameter _EventDescription_W = null;
			private AggregateParameter _UserID_W = null;
			private AggregateParameter _ByUserName_W = null;
			private AggregateParameter _EventTime_W = null;

			public void AggregateClauseReset()
			{
				_ID_W = null;
				_Identifier_W = null;
				_RequisitionID_W = null;
				_EventName_W = null;
				_EventDescription_W = null;
				_UserID_W = null;
				_ByUserName_W = null;
				_EventTime_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private BusinessEntity _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	
		protected override IDbCommand GetInsertCommand() 
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_LogRequisitionEventsInsert]";
	
			CreateParameters(cmd);
			
			SqlParameter p;
			p = cmd.Parameters[Parameters.ID.ParameterName];
			p.Direction = ParameterDirection.Output;
    
			return cmd;
		}
	
		protected override IDbCommand GetUpdateCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_LogRequisitionEventsUpdate]";
	
			CreateParameters(cmd);
			      
			return cmd;
		}
	
		protected override IDbCommand GetDeleteCommand()
		{
		
			SqlCommand cmd = new SqlCommand();
			cmd.CommandType = CommandType.StoredProcedure;
			cmd.CommandText = "[" + this.SchemaStoredProcedure + "proc_LogRequisitionEventsDelete]";
	
			SqlParameter p;
			p = cmd.Parameters.Add(Parameters.ID);
			p.SourceColumn = ColumnNames.ID;
			p.SourceVersion = DataRowVersion.Current;

  
			return cmd;
		}
		
		private IDbCommand CreateParameters(SqlCommand cmd)
		{
			SqlParameter p;
		
			p = cmd.Parameters.Add(Parameters.ID);
			p.SourceColumn = ColumnNames.ID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.Identifier);
			p.SourceColumn = ColumnNames.Identifier;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.RequisitionID);
			p.SourceColumn = ColumnNames.RequisitionID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.EventName);
			p.SourceColumn = ColumnNames.EventName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.EventDescription);
			p.SourceColumn = ColumnNames.EventDescription;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.UserID);
			p.SourceColumn = ColumnNames.UserID;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.ByUserName);
			p.SourceColumn = ColumnNames.ByUserName;
			p.SourceVersion = DataRowVersion.Current;

			p = cmd.Parameters.Add(Parameters.EventTime);
			p.SourceColumn = ColumnNames.EventTime;
			p.SourceVersion = DataRowVersion.Current;


			return cmd;
		}
	}
}
